import Head from 'next/head'
import Image from 'next/image'
import { GraphQLClient, gql } from 'graphql-request'
import { useEffect, useState } from 'react'
import Link from 'next/link'


const graphcms = new GraphQLClient(
  'https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clcluf3o42j9j01ug2baub5m3/master')

const QUERY = gql`
    {
      authors {
        avatar {
          url
        }
        name
        slug
        role
        bio
        socials
        researches {
          title
          slug
          createdAt
          seo
          authors {
            name
          }
        }
      }
    }
`
const SLUGLIST = gql`
    {
        authors {
            slug
          }
    }
    `

export async function getStaticProps() {
  const authors = await graphcms.request(QUERY)
  return {
    props: {
      authors,
    },
    revalidate: 10,
  }
}

export default function Home(authors: any) {
  console.log(authors.authors.authors)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <div className='flex flex-col gap-10'>
          {
            authors.authors.authors.map((author: any, index: any) => (
              <div key={index} className='flex gap-4 border-b-2 items-center'>
                <img src={author.avatar.url} alt={author.name} width="100px" height="100px" />
                <Link href={"/Authors/" + author.slug}>{author.name}</Link>
              </div>
            ))

          }
        </div>
      </main>
    </>
  )
}
